### ISSUE TITLE
Implementar envios de email

### ISSUE THREAD

**Issue by andersondalmina** [Coderockr/vitrine-social#180]
## What is the objective? (Context)
Implementar sistema de envios de emails.
- [ ] Utilizar sistema para enviar emails de contatos para organizações através da chamada need/id/response
<img width="1440" alt="emailorganization" src="https://user-images.githubusercontent.com/2267327/41483675-5a77b3b0-70b0-11e8-9e7e-3553a2068814.png">

- [x] Utilizar sistema para enviar emails de contatos para a Vitrine Social
<img width="1440" alt="emailvitrine" src="https://user-images.githubusercontent.com/2267327/41483676-5cccf2a6-70b0-11e8-910f-4950b0b0bcae.png">

## What is the current behavior?
Não existe envios de emails.

**Comment by juliabpp** [comment]
@andersondalmina revisar need/id/response que não está enviando o email
