### ISSUE TITLE
Definir hospedagem

### ISSUE THREAD

**Issue by eminetto** [Coderockr/vitrine-social#2]
Talvez pedir para algum fornecedor de hospedagem patrocinar?

**Comment by eminetto** [comment]
É possível usar a conta free por 12 meses da Amazon para hospedar um servidor básico

**Comment by andersondalmina** [comment]
Amazon AWS: Conforme o Elton comentou, podemos utilizar o plano free por 12 meses com as intâncias EC2 e RDS (acho que é o que precisamos), após isso os valores seriam em média R$ 9 a EC2 e $10 a RDS (Mensais). Acho que é a melhor solução. https://aws.amazon.com/pt/free/

Heroku: O plano free do Heroku funciona meio diferente. Ele não tem prazo de validade, mas após 30 min de inatividade da aplicação, o "server" dorme. Dai o próximo acesso demora mais pois precisa ativar o "server" novamente. Pode ficar ativo até 450 horas/mensais pelo que entendi, após isso o "server" é desligado até o mês seguinte. (Obs: um mês tem cerca de 720 horas). https://www.heroku.com/pricing

GetUp: Verifiquei que eles tem um período free para testes e após isso a intância de 512MB de ram fica R$ 18,25 mensais e a de 1GB R$ 133,10. Porém podemos entrar em contato com eles para alguma forma de parceria, sei lá. https://getupcloud.com/pt-br/precos/

**Comment by eminetto** [comment]
A Amazon deu um bug na hora de validar a nova conta (não conseguiu fazer o call pra mim) e bloqueou a criação por 12 horas
Vamos de Google Cloud que tmb tem 12 meses free

**Comment by andersondalmina** [comment]
Beleza
