### ISSUE TITLE
Enviar email de contato para Organização

### ISSUE THREAD

**Issue by andersondalmina** [Coderockr/vitrine-social#212]
## What is the objective? (Context)
Quando o usuário se interessar em ajudar a organização com alguma necessidade ele vai entrar em contato por um formulário. Enviar os dados desse formulário por email para a organização.

## What is the current behavior?
Já existe esse formulário mas ainda não foi implementado o envio de email.

## Possible Solution
Criar um template no sendgrid para esse email e enviar pelo service mail.

**Comment by juliabpp** [comment]
@andersondalmina revisar esta tarefa pois não estou recebendo os emails
