### ISSUE TITLE
Move frontend dependencies -> devDependencies

### ISSUE THREAD

**Issue by vcapretz** [Coderockr/vitrine-social#334]
## What is the objective? (Context)

Hey folks 👋, the project is awesome and the layout looks very nice! It also seems super organized, congrats on it! 

I was checking the `frontend/` folder and saw some dependencies that can/should be declared as devDependencies, such as webpack and babel related (also, their plugins), since they are mostly required for building the dev environment and also bundling stuff. 

Do you think we can move those or do you see any other constraints? If you give me the green light I can send the PR!

**Comment by lucassabreu** [comment]
hi @vcapretz, feel free to make these changes :wink:
