### ISSUE TITLE
Bump React on frontend to latest 16

### ISSUE THREAD

**Issue by vcapretz** [Coderockr/vitrine-social#335]
## What is the objective? (Context)

Do you think we can bump react to v16, saw it's still on 15 and there are some very nice new features and patterns available on 16, also React team is preparing for some breaking changes on v17 (such as deprecating some lifecycle methods) and would be nice to start adopting them!

Let me know your thoughts! 😄

**Comment by RaonyMarcondes** [comment]
Of course, it would be nice to upgrade to React 16, but we need to be careful to that upgrade doesn't break components, or containers as side effects, or generate lifecycle warnings on Lint.

**Comment by vcapretz** [comment]
some warnings are probably gonna be generated since React is doing so to alert developers that things will change, I'll try to bump it and see all the necessary changes and maybe split them in more than one PR! 💃
