### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by lucassabreu** [Coderockr/vitrine-social#35]
### Realizar login [POST]

+ Request Login
    + Headers
            Accept: application/json
            Content-Type: application/json
    + Attributes (Login)

+ Response 200 (application/json)
    + Attributes
        + organization (BaseOrganization)
        + token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ (string)

+ Response 404 (application/json)
    + Attributes (Error)

**Comment by jalxes** [comment]
redundante com #29
