### ISSUE TITLE
Pesquisa de Necessidades

### ISSUE THREAD

**Issue by lucassabreu** [Coderockr/vitrine-social#37]
### Fazer busca [GET]

+ Parameters
    + text: texto a ser pesquisado (string, optional) - Texto a ser pesquidado
    + categories: 1,2,3 (string, optional) - Ids das categorias
    + org: 1 (number, optional) - Id da entidade para filtrar
    + page: 1 (number, optional) - Paginação (vai trazer sempre 10 por página)

+ Request Busca das necessidades

    + Headers

            Accept: application/json
            Content-Type: application/json

+ Response 200 (application/json)
    + Attributes (array[BaseNeed])

**Comment by juliabpp** [comment]
@andersondalmina adicionar um orderBy por created date e por update date, pra saber quais foram criadas mais recentemente ou se quiser ver as que foram atualizadas mais recentemente. Padrão é as que foram criadas mais recentemente

- [ ] ordenação createdAt crescente ou decrescente
- [ ] ordenação updatedAt crescente ou decrescente
